AlgorithmLibrary/CocktailSort.js
Cocktail shaker sort now works!
=> fixed very minor bug in cocktail.js; there was an extraneous z

AlgorithmLibrary/DequeLL.js, DequeLL.html, index.html
https://github.com/RodrigoDLPontes/visualization-tool/projects/1#card-28297027
=> Added LinkedList Deque

AlgorithmLibrary/QueueArray.js, AlgorithmLibrary/SkipList.js, index.html
I went through the Low Priority section of the bugs and grabbed some low-hanging fruit.
Addresses these cards: 
- Change "Dijkstra" to Dijkstra's" in home page
- Change wording on "Add randomly" button in SkipLists to make it more clear that the number of 
heads is what is randomized (so it still needs a value)
- Change "ArrayList" in Stack and Queue titles in home page to "Array"
- Change labels from array-backed Queue from "head" and "tail" to "front" and "back"
Looking over it, I'm thinking it may actually be better to change `Add random amount` to `Add random quantity`, but what do you guys think?
=> Various low priority fixes

src/algo/Heap.js
=> Remove conversion to strings in buildheap

src/algo/ClosedHash.js
=> Fixed bug when adding duplicated to HashMap (Probing) 

src/algo/StackArray.js, src/algo/StackLL.js
=> Changed 'Top' to 'Size' and 'Head' 

src/algo/SelectionSort.js
Closes #77
Added radio button selector for min/max sorts in selection sort, which changes the tracing of the algorithm for each option.
=> Added option to sort via min or max value in selection sort

src/algo/ClosedHash.js
yo
added more labels and highlighting stuff
- showing when we're saving a removed entry index
- adding descriptions when we move forward
- descriptions to if we're adding at deleted or null spot
- showing termination upon seeing null spot
- change size to 13
- center table
=> cooler labels

src/algo/BST.js
=> Add pre/in/post order traversals

src/algo/Algorithm.js, src/algo/ArrayList.js
=> Array list resize migrated

src/algo/DequeArray.js
Closes #92 
Did not implement the wrong version of DequeArray this time 👀
AddFirst (which doesn't loop around the entire array):
AddLast:
And, as always, good ol' step back:
=> Deque array resize

src/algo/QuickSelect.js, src/algo/QuickSort.js
We already had random pivot but now it's explicit
Also add median pivot
=> Add median/random pivot options to quicksort and quickselect

src/algo/ClosedHash.js
Ok so I guess that was a no on updating the primes
=> Remove changing primes with doublehashing

src/algo/RabinKarp.js
Adds the ability to change the base value in Rabin-Karp hash calculation
=> Add ability to change base in Rabin-Karp

src/algo/RabinKarp.js
Changed the Rabin-Karp to actually use the rolling hash algorithm that we teach in class.
=> Change all Rabin-Karp hash calculations so they actually work

src/algo/StackLL.js
- Style reflects the style used in HeapSort & LCS for pseudocode functionality.
- Addresses issue #127 - will continue to add for other algo!
=> Adding pseudocode highlighting to stack LL algo

src/algo/LinkedList.js
- Nothing much to it, just added a head pointer for SLL 
- Addresses #132
=> Added a head pointer for SLL

src/algo/BoyerMoore.js, src/algo/BruteForce.js, src/algo/KMP.js, src/algo/RabinKarp.js
addresses #159
Pattern matching algorithms now display comparison counts as they run!
Done in the same way as sorting algos and designed to match the comparison counts expected by our homework.
=> Comparison counts for String searching algos

src/algo/Algorithm.js, src/algo/BubbleSort.js, src/algo/CocktailSort.js, src/algo/InsertionSort.js, src/algo/LSDRadix.js, src/algo/MergeSort.js, src/algo/QuickSelect.js, src/algo/QuickSort.js, src/algo/SelectionSort.js
Addresses #127 
All of the sorting algorithms have animated pseudocode!
- All of the code was adapted from course modules
- A couple of our JS implementations were slightly different than our Java implementations, but the pseudocode is designed to match course content
- I shifted / condensed mergeSort a little bit so that the code could fit, it now has max length 15 like heapSort
I want to eventually clean up the display, but it's probably good to add more pseudocode now.
=> Sorting Pseudocode

src/algo/CocktailSort.js, src/algo/QuickSort.js, src/algo/SelectionSort.js
- Closes #165 
- Improves Quicksort highlighting
- Fixes Selection Sort code to better match animation
=> Fixes a couple pseudocode bugs

src/algo/BoyerMoore.js, src/examples/ExampleModals.js
Closes #130 
This adds the Galil Rule as an optional enhancement to Boyer Moore that's controlled with a button on the top bar.
When active, shifts are optimized after a full match using the period, which is calculated during preprocessing.
=> Galil Rule for Boyer Moore

src/algo/CircularlyLinkedList.js, src/algo/DequeLL.js, src/algo/DoublyLinkedList.js
Closes #131, closes #133, closes #137.
Uses the same style as the existing head and tail pointers in SLL, Queue, etc.
=> Adds head and tail pointers to CLL, DLL and LLDeque

src/algo/BST.js, src/components/Footer.js
closes #150 
Also refactors the traversals a little:
- Pseudocode uses superclass method now
- LevelOrder uses same mechanisms as other traversals
=> Fixes level order clear, refactors pseudocode

src/algo/Algorithm.js, src/algo/BST.js
=> adds pseudocode and queue to BST level order traversal

src/algo/Algorithm.js, src/algo/ClosedHash.js, src/algo/Hash.js, src/css/AlgoScreen.css, src/css/App.css, src/screens/AboutScreen.js
This improves the user experience by creating a more accessible/responsive control bar. It also addresses the undesirable "bloat" in HashMaps Probing by using a drop down menu to present options. Due to browser specific CSS, the drop down may render differently across browsers. 
I believe this and previous UI updates also address issue #140 
Further work to follow up this PR includes:
- integrating the dropdown into other visualizations that can benefit from the saved space 
- identifying/addressing other cross browser inconsistencies
=> Control bar updates

src/algo/ClosedHash.js, src/algo/Hash.js, src/algo/OpenHash.js
=> hashmap fix

src/components/Header.js, src/screens/AlgoScreen.js
=> Track the number of times the theme is toggled in Google Analytics

src/algo/BoyerMoore.js, src/algo/BruteForce.js, src/algo/KMP.js, src/algo/RabinKarp.js
This adds table indices to all pattern matching animations making it easier to track matches.
=> Add indices to pattern matching tables

src/algo/BoyerMoore.js
=> fix galil toggle bug

src/algo/BST.js, src/algo/BoyerMoore.js, src/algo/Dijkstras.js
=> Fix pseudocode indentation

src/algo/LinkedList.js, src/anim/AnimatedLabel.js, src/anim/AnimationMain.js, src/css/AlgoScreen.css, src/examples/ExampleModals.js
This adds the option of a tail pointer to the Singly Linked List visualization. This also adds more animation steps to the SLL operations to make the visualizations more intuitive.
=> Add tail pointer to SLL

src/algo/LCS.js
to align with our module video formatting
=> switch LCS string positions

src/algo/Hash.js
=> Fixed HashMap crash bug

package-lock.json, src/algo/QuickSort.js, src/anim/AnimatedLabel.js, src/anim/AnimationMain.js, src/anim/ObjectManager.js
This adds i and j text labels to more clearly track i and j during partitioning. This is a simple feature that can be added to all algorithms with moving pointers making it a good first time contribution #258.
=> Add i and j labels to Quicksort

src/algo/AVL.js, src/algo/ArrayList.js, src/algo/BST.js, src/algo/BTree.js, src/algo/CircularlyLinkedList.js, src/algo/ClosedHash.js, src/algo/DequeArray.js, src/algo/DequeLL.js, src/algo/DoublyLinkedList.js, src/algo/Hash.js, src/algo/LinkedList.js, src/algo/OpenHash.js, src/algo/QueueArray.js, src/algo/QueueLL.js, src/algo/SkipList.js, src/algo/SplayTree.js, src/algo/StackArray.js, src/algo/StackLL.js
Added for 4 lists (ArrayList, SLL, DLL, CSLL)
If others are good with the functionality, I'll do the rest of the algorithms/data structures
addresses issue #256
=> Random Data Entry for Lists 

src/algo/ClosedHash.js, src/algo/OpenHash.js
=> Fix duplicate key issue in HashMap

src/algo/OpenHash.js
Addresses #269.
@piater thank you for catching this bug! Feel free to review the changes and then this can be merged in.
=> Fix open hash find value bug

src/algo/BoyerMoore.js, src/algo/BruteForce.js, src/algo/KMP.js, src/algo/RabinKarp.js
This adds a row count to all pattern matching tables making it easier to track alignments.
=> Add row count to pattern matching tables

src/AlgoList.js, src/algo/ArrayList.js, src/algo/BST.js, src/algo/CircularlyLinkedList.js, src/algo/DequeArray.js, src/algo/DoublyLinkedList.js, src/algo/QueueArray.js, src/css/App.css
Addresses #127. 
This adds pseudocode with highlighting to ArrayDeque and BST.
=> Add pseudocode to ArrayDeque and BST

src/algo/ArrayList.js, src/algo/CircularlyLinkedList.js, src/algo/DequeArray.js, src/algo/DequeLL.js, src/algo/DoublyLinkedList.js, src/algo/Heap.js, src/algo/LinkedList.js, src/algo/QueueArray.js, src/algo/QueueLL.js, src/algo/StackArray.js, src/algo/StackLL.js
This prevents duplicate random input elements in all data structures.
=> Make random input unique

src/algo/QueueArray.js
=> Array Queue random front

src/algo/ArrayList.js, src/algo/DequeArray.js, src/algo/QueueArray.js, src/algo/StackArray.js
=> Reset expanded arrays when clear button is pressed

src/algo/Algorithm.js
=> allow int input from numpad

src/algo/ArrayList.js, src/algo/CircularlyLinkedList.js, src/algo/DoublyLinkedList.js, src/algo/LinkedList.js
quick fix for animation issues
=> skip back ugh

src/algo/Algorithm.js, src/algo/ArrayList.js, src/algo/DequeArray.js, src/algo/DequeLL.js, src/algo/Hash.js, src/algo/Heap.js, src/algo/QueueArray.js, src/algo/QueueLL.js, src/algo/StackArray.js, src/algo/StackLL.js
Prevents spaces from being used in all inputs
Resolves inconsistencies in:
- ArrayList
- DequeArray
- DequeLL
- Hashmap
- Heap
- QueueArray
- QueueLL
- StackArray
- StackLL
Solves #280
=> Fix inconsistent input types

src/algo/SelectionSort.js
Since it's typically taught this way in lecture (at least for the last few semesters) I think it would be more convenient to default to max mode. #306
=> Make SelectionSort default to Maximum

src/algo/ClosedHash.js, src/algo/OpenHash.js
Closes #302 
The code was pretty much there already, just missing the logic to rehash the key and pass through animation commands.
https://github.com/RodrigoDLPontes/visualization-tool/assets/67525591/564dc625-543e-4bbe-bc17-d3d793514ce0
Example from the issue :D
=> fix probing resize issue

src/css/App.css, src/screens/HomeScreen.js
=> Add feedback banner to home page

src/pseudocode.json
Fix in pseudocode.json of BST pseudocode
=> Update BST 'findH' english pseudocode

src/algo/Quickselect.js, src/algo/Quicksort.js, src/examples/ExampleModals.js
=> Add Set Pivot Index Option to Quicksort/select

src/components/AlgorithmNotFound404.js, src/modals/BigOModals.js, src/screens/AlgoScreen.js
- I was bored in a Saturday night and for some reason I ended up in csvistools repo. I saw that a lot of it was old code and decided to improve it.
- Updated `AlgoScreen` component from class component to functional component
- Created a component for the 404 screen
- Removed some unused variables and states
- Destructured `algoMap` to make the code more readable
1. I did not test all of the functionalities of all different data structures.
3. Someone seems to have added a Vercel bot by mistake that fails PRs.
=> Updating AlgoScreen from class component to functional component

src/css/App.css, src/screens/HomeScreen.js
- Created a search bar to filter out the different DSAs and algorithms. 
- [Search bar issue](https://github.com/RodrigoDLPontes/visualization-tool/issues/298)
https://github.com/user-attachments/assets/bc8af747-9d64-4531-a4ac-51c4c6c3fa55
- Please, let me know what you think about the design. I did it pretty quickly, I like how it looks but open to feedback 👍
=> Create a search bar
