src/algo/BubbleSort.js, src/algo/CocktailSort.js, src/algo/Heap.js, src/algo/InsertionSort.js, src/algo/LSDRadix.js, src/algo/MergeSort.js, src/algo/QuickSelect.js, src/algo/SelectionSort.js
Addresses #26 
`0` is a falsy value in JS, so `.filter(x => x)` was removing `0` from the input array.
`.filter(x => !Number.isNaN(x))` correctly removes `NaN` while preserving `0`.
Correctly preserves 0:
Correctly removes invalid inputs:
=> Fixed input validation for sorts

.gitignore, src/algo/QueueArray.js
Hello!
I added some functionality for issue #47 .
'Head' is now renamed to 'Front' and acts just like front did.
'Tail' now tracks the size and is renamed to 'Size'
There's now some labels about how enqueueing works:
And it moves too 😎
Finally
=> #47 head to front and tail to size

src/algo/StackArray.js
Closes #61 
Added the ability to resize Stack Arrays when they're full (again, but working this time)
Actually very much _unlike_ ArrayList resizing contrary to what I mentioned in my last PR. For StackArray, keeping `this.arrayData` works perfectly fine, and everything is reverted properly upon stepping back.
To reiterate, I changed the initial minimum array size to 7 and the maximum amount of resizes to 2. Also, I changed the placement of the new resized array so everything shows up on the screen. Might be a little awkward looking, so I can change if necessary:
=> StackArray Resize

src/algo/QueueArray.js
Closes #66
Closes #60
Closes #56 
and I think closes #53 (although this issue might've already been fixed, not entirely sure)
QueueArray Resize is here!
For this resize implementation, I chose to show each individual element moving arrays one at a time, since having them move all at once might be slightly confusing/disorienting if the front isn't at index 0. I can go back and add this for ArrayList and StackArray too, but for those I personally think it takes up too much time.
I also chose to have the addition of the new element happen after the entire resize has been completed, unlike with StackArray. I can go back and change StackArrays to do this as well since it's a more common implementation to have resize separate from the addition. However, it could be nice to have them stay …
=> Queue array resize

src/algo/ClosedHash.js, src/algo/Hash.js, src/algo/OpenHash.js
Closes #106
Closes #103 
Closes #102 
It's big hashing time
Hashing resize has been implemented (for probing). External hashing to follow soon, and <key, value> pairs after that.
This PR does quiiiite a few things on top of just implementing probing hashmap resize:
- Adds a label that keeps track of the index calculation while probing to give a little more clarification as to how the indices are being reached
- Adds a changeable load factor that dictates when a resize will happen (and yes, you can make this LF 0 for immediate resizes)
- Adds a maximum array size of 55 (for a total of 2 resizes, consistent with the other resize PR's)
- Changes DoubleHashing's prime number to the next lowest prime after each resize (e.g. 23 after the first resize and 53 after the second) [I'm not sure if …
=> Closed Hash Resize

src/algo/KMP.js
An key feature of the KMP algorithm is the consultation of _f_[_k_] on encountering a mismatch following one or more matches, where _f_ is the failure table and _k_ is the last-matched index into the pattern. I added a visualization of this by highlighting _pattern_[_k_] in the array, and  _pattern_[_k_] and _f_[_k_] in the failure table.
I needed this for my own purposes and think it adds general value to this visualization, so here it is if you like.
This closes #111.
(A similar highlight might be added to `buildFailureTable()`, but this already uses two different-colored highlight circles, and the correspondences are quite obvious even without this highlight. So I think here it would hurt more than help.)
=> KMP: highlight active failure table entry

src/algo/QueueArray.js
ArrayQueue Clear() now clears the entire array and resets the 'front' pointer
=> Fix ArrayQueue Clear

src/algo/HeapSort.js, src/algo/LCS.js
Closes #144 
Updated LCS pseudocode for clarity and to include the traceback portion of the algorithm. Also changed the formatting of LCS and HeapSort to match.
Before:
After:
Additionally, added highlighting of indices to LCS backtracing:
=> Update pseudocode for LCS and MergeSort, add more pseudocode for LCS

src/algo/Heap.js
closes #129 
Heap can resize now!
The initial array is length 8, and doubles each time a resize is necessary (up to length 32, the original max length).
Buildheap also implements this change, with the backing array initialized to 2*n (unless n >= 16).
Also, on clear the array is reset to its initial capacity. This felt a little more consistent with how we implement clear() on homework.
=> Heap/PQ Resize

src/algo/BST.js
- Implements pseudocode highlighting for depth-first traversals. The pseudocode for these are the recursive implementations and are from the course modules on canvas. 
- Added a helper function called `setUpPseudocode(tailoredCode) ` in BST.js that parses an array of pseudocode & renders it in addition to generating the codeID array (for highlighting & unhighlighting). Later down the line, should prob refactor this and make it a module to import into the algo files to avoid repetitive code.
- Because of this, added an extra parameter to each traversal algo called 'passedCodeID' to avoid re-rendering the pseudocode on top of itself on the page during every recursive call.
- This PR excludes the pseudocode highlighting functionality for level order traversals. This is because we don't have …
=> Pseudocode highlighting for BST Depth First Traversals

src/algo/ClosedHash.js, src/algo/OpenHash.js
Closes #125 
Big changes with this PR - added the ability to resize the external chaining hashmap!! 
In doing so, a visual overhaul was required to fit the length of the array, and unfortunately there is only room for one resize with the way it currently performs the resize operation. There is potential in the future to allow another resize if we allow array wrapping, but currently only one is available.
Before adding <4, ivan>:
After adding <4, ivan>:
=> Add the ability to resize External Chaining Hashmap

src/algo/SkipList.js
closes #48 and #121 
- Fixes the issue where some layers looked lopsided after a duplicate addition
- Addresses the discussion on #48, so when a duplicate is added with more heads than the previous value those new layers are filled in
=> Fix Handling of SkipList Duplicates

src/algo/BTree.js
Now there's a choice between predecessor and successor when removing! 
It works in the same way as BST/AVL, but more _zesty_ because it's a 2-4 tree
closes #104
=> 2-4 Tree Predecessor/Successor

src/algo/BubbleSort.js, src/algo/CocktailSort.js, src/algo/InsertionSort.js, src/algo/MergeSort.js, src/algo/QueueArray.js, src/algo/QuickSelect.js, src/algo/QuickSort.js, src/algo/SelectionSort.js
closes #158 
Sorting algorithms display comparison counts while running! 
Heapsort and LSD Radix don't have this feature because their methods of sorting don't directly compare objects in the typical sense. 
The algorithms are all consistent with the way they are taught in 1332 and the comparison counts match the requirements of our homework (at least it seems that way).
=> Comparison Count for Sorting Algorithms

src/algo/OpenHash.js
The size wasn't being decremented when you remove from the map, causing early resizing.
closes #163
=> External Chaining Resizing Issue

src/algo/BoyerMoore.js, src/algo/BruteForce.js, src/algo/KMP.js, src/algo/RabinKarp.js
Adds pseudocode for Boyer Moore (including the Galil Rule), KMP, Rabin Karp and Brute Force.
For each of them, the pseudocode isn't generated until the algorithm starts (because the pattern space is variable). Code for the BM last occurrence table and KMP failure table are also included, and disappear after preprocessing is finished.
=> Add Pattern Matching Pseudocode

src/algo/BTree.js
closes #197 
The way that data is currently removed from the tree is not ideal. Data remains in the node after removed, and the displayed node is just resized. It was our duplicate handling that lead to the error, but I want to fix this node structure eventually.
closes #198
This was basically a NPE happening when the root of the tree gets deleted and then attempted to be accessed later...Another patch that should be looked at in more detail later
=> a couple fixes for 2-4 Trees

src/algo/SkipList.js
This is a simple fix that truly randomizes skip lists. The previous calculation was dependent on the size of the skiplist. So the very first time a user called add with random heads, it will always give you 0 heads. This is now fixed
=> Make SkipLists random again!

package-lock.json, package.json, src/algo/Algorithm.js, src/algo/LSDRadix.js, src/anim/AnimationMain.js, src/examples/ExampleModals.js
This addresses issues #138 and #139. Users now have the option to sort negative numbers by a checkbox selection. The maximum value has been capped to 6 characters making [-99999, 999999] the range of sortable numbers. Capping $k$ at 6 keeps the input array reasonably sized while still demonstrating the importance of $k$ in radix sort.
=> Add negative number sorting capability to radix sort

src/algo/ClosedHash.js, src/algo/Hash.js
This addresses two bugs in HashMaps. In closed addressing, colliding entries will clump together. Also keys with leading zeros were interpreted as distinct when hashing integers. That is "9" and "09" were treated as different keys when they are effectively the same integer key. These are now fixed.
=> Hashmap fixes

src/algo/Hash.js
This addresses #251. A percent sign is used for the load factor. The field has been limited to two characters eliminating most invalid inputs. Other invalid inputs default to the default load factor.
=> Use percent sign for HashMap load factor

public/404.html, public/index.html
This adds a meta description tag which was previously empty on search results:
=> Search engine optimization

.gitignore, src/algo/Algorithm.js, src/algo/ArrayList.js, src/algo/DFS.js, src/algo/DequeArray.js, src/algo/Dijkstras.js, src/algo/DoublyLinkedList.js, src/algo/Hash.js, src/algo/Kruskals.js, src/algo/QueueArray.js, src/algo/QueueLL.js, src/algo/StackArray.js, src/algo/StackLL.js, src/anim/AnimationMain.js, src/anim/ObjectManager.js, src/components/Header.js, src/css/AlgoScreen.css, src/screens/AlgoScreen.js
Closes #291
All animated objects are drawn on certain "layers" on the canvas. With these changes, the pseudocode is drawn on its own layer that can be toggled on/off with a React button.
- By default the pseudocode is shown, mainly since this is what users are used to by now and the button to activate the code may not be super apparent.
- Code is drawn on layer '32' just for fun 😄, but this layer is now reserved exclusively for pseudocode 
- Changed appearance of example modal button to match code toggle: both buttons are theme dependent and show when they are active/inactive.
https://github.com/RodrigoDLPontes/visualization-tool/assets/67525591/917939a2-210b-4281-a627-39730a8949e8
https://github.com/RodrigoDLPontes/visualization-tool/assets/67525591/21795968-57b4-4eb7-a8da-be2693fa4eea
=> Add Pseudocode Toggle

src/algo/Algorithm.js, src/algo/ClosedHash.js, src/algo/Hash.js, src/algo/OpenHash.js
The old probing type formulas were a little confusing. This hopefully makes them more clear.
I also changed drop-downs to accept an array of arrays for the options now - for the option text and value.
=> update probe formulas, dropdown logic

src/anim/AnimatedLabel.js
Addresses #243
The issue was that the label wasn't waiting for the font to load before it was drawn, causing it to be rendered with the default font on first page load. This update should address that issue by adding a new async function that is called only when using the source code font.
=> fix font loading issue

src/algo/BTree.js
The spacing of nodes on the 2-4 tree is very small, making it difficult to distinguish between different nodes. This pull request simply changes the NODE_SPACING variable from 3 to 15, increasing the gap and making it easier to visualize the tree.
The difference can be seen in the pictures below:
**Before**
**After**
=> Increase NODE_SPACING from 3 to 15

src/algo/BST.js
The highlighting for the BST remove method seems a smidge off, as seen here:
I'm guessing the code needed to be changed at some point and the highlighting was never updated. The changes attached to this PR should hopefully fix most of those issues. Thanks a million for such a convenient visualizer!
=> Fix BST deletion pseudocode highlighting
